# Generated by Django 4.2.17 on 2024-12-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
