#TODO look why server dont compose (root dont works too)

services:
  web:
    hostname: web
    build: docker/apache
    volumes:
      - ./html:/web
      - ./vhost/server1/server1.conf:/etc/apache2/sites-enabled/server1.conf
      - ./vhost/server2/server2.conf:/etc/apache2/sites-enabled/server2.conf
      - ./html/alias:/srv
      - ./certificados:/certificados
    networks:
      rede_test:
        aliases:
          - server1.lan
          - www.server1.lan
          - server2.lan
          - www.server2.lan

  client:
    hostname: client
    build: docker/client
    networks:
      - rede_test
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

networks:
  rede_test:
