# Generated by Django 4.2.16 on 2024-11-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
