# Generated by Django 4.2.17 on 2024-12-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='surname',
            field=models.CharField(max_length=250),
        ),
    ]
